[workspace]
members = ["contracts/governance"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["anihdev"]

[workspace.dependencies]
ckb-std = { version = "0.16.4", default-features = false, features = ["allocator", "calc-hash", "ckb-types", "dummy-atomic", "libc"] }

[profile.release]
panic = "abort"
overflow-checks = true
lto = true
codegen-units = 1
strip = true
